// C H A N G E S

/* Changes in the Welcome Window
I added four new buttons:

Add Student – To add a new student.
Delete Student – To remove a student.
Update Student – To change student details.
Logout – To exit the system. */

/* These buttons make it easy to manage students. They give users quick access to each function.
--------------------------------------------------------------------------------------------------*/

/* Separate Windows for Each Feature
Each button opens a new window for that feature:

Add Student Window – Lets users add student details.
Delete Student Window – Helps remove a student from the system.
Update Student Window – Allows changes to a student’s details.
Logout – Closes the program to keep it secure. */

/* Having separate windows makes the system easier to use and understand.
Each part works on its own, so there are fewer errors.
----------------------------------------------------------------------------------------------------*/

//Navigation Controls

/*Each window has a Back button (except Logout) to return to the Welcome Window.
This helps users move around the system easily. They won’t get stuck in one place.
-----------------------------------------------------------------------------------------------------*/


package GUIapp;

import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

public class LoginPage extends javax.swing.JFrame {

    
   private static final String filePath = "C:\\Users\\raymark\\Documents\\NetBeansProjects\\AT4_Corbita\\src\\users.json";    
    
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        welcome = new javax.swing.JLabel();
        br = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 76, 78, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 132, 78, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 73, 218, -1));
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 129, 218, -1));

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 193, 99, -1));

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 193, 100, -1));

        welcome.setBackground(new java.awt.Color(255, 255, 255));
        welcome.setFont(new java.awt.Font("YouYuan", 3, 24)); // NOI18N
        welcome.setForeground(new java.awt.Color(255, 255, 255));
        welcome.setText("STUDENT MANAGER");
        jPanel1.add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 200, 41));

        br.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        jPanel1.add(br, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     String username = jTextField1.getText();
    String password = new String(jPasswordField1.getPassword());


    if (authenticateUser(username, password)) {
            JOptionPane.showMessageDialog(this, "Login Successful!");
            this.dispose(); // Close login window
            new WelcomeWindow().setVisible(true); 
        } else {
        JOptionPane.showMessageDialog(this, "Incorrect Input!");
    }
         
    }//GEN-LAST:event_jButton1ActionPerformed
         private boolean authenticateUser(String username, String password) {
        JSONParser parser = new JSONParser();
        try (FileReader reader = new FileReader(filePath)) {
            JSONObject jsonObject = (JSONObject) parser.parse(reader);
            JSONArray usersArray = (JSONArray) jsonObject.get("users");

            for (Object obj : usersArray) {
                JSONObject user = (JSONObject) obj;
                String jsonUsername = (String) user.get("username");
                String jsonPassword = (String) user.get("password");

                if (username.equals(jsonUsername) && password.equals(jsonPassword)) {
                    return true; // Successful login
                }
            }
        } catch (IOException | ParseException e) {
            e.printStackTrace();
        }
        return false; 
        }
/* THIS FEATURE CHECKS IF THE ENTERED USERNAME AND PASSWORD MATCH ANY USER IN
   JSON FILE IF THE USER DATA ARE CORRECT, IT WILL PROCEED TO THE WELCOME      
   WINDOW. IF NOT IT SHOWS AN ERROR MESSAGE. */    
         
     
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      jTextField1.setText("");
        jPasswordField1.setText("");      
    }//GEN-LAST:event_jButton2ActionPerformed
// THESE FUNCTION WILL CLEAR ALL THE TEXT THAT YOU HAVE INPUT IN THE FIELD
    
    
    
    private String validateLogin(String username, String password) {
        JSONParser parser = new JSONParser();
        try (FileReader reader = new FileReader("users.json")) {
            JSONObject jsonObject = (JSONObject) parser.parse(reader);
            JSONArray usersArray = (JSONArray) jsonObject.get("users");

            for (Object obj : usersArray) {
                JSONObject user = (JSONObject) obj;
                String jsonUsername = (String) user.get("username");
                String jsonPassword = (String) user.get("password");
                String userType = (String) user.get("type");

                if (username.equals(jsonUsername) && password.equals(jsonPassword)) {
                    return userType; 
                }
            }
        } catch (IOException | ParseException e) {
            e.printStackTrace();
        }    
     return null; 
    }
/* THIS FEATURE CHECKS IF THE USERNAME AND PASSWORD MATCH A USER IN JSON FILE
   IF THEY MATCH IT WILL PROCEED. IF NOT IT WILL NOT PROCEED TO WELCOME WINDOW */
    
  
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new LoginPage().setVisible(true));
     //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel br;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
